### ISSUE TITLE
Own presence shown as offline after a while with presence writer worker enabled

### ISSUE THREAD

**Issue by jaywink** [matrix-org/synapse#10027]
### Description

We're trialing presence workers on a few EMS hosts and for a while the new presence writer worker worked fine. After a few days, both of the hosts stopped reporting presence online for the user themselves. A restart of Synapse made presence show correctly for self again.

### Version information

- **Version**: v1.34.0
- **Platform**: EMS/Docker

Please ping for host names for logs access.

**Comment by babolivier** [comment]
I think this is more widespread than just your own presence; from vector.modular.im I'm seeing both my work account (on vector.modular.im) and my personal account (on abolivier.bzh) as offline even though they're both online.

**Comment by jaywink** [comment]
Yeah currently I can't see anyone from vector online even if I'm actively talking to one in a dm.

**Comment by anoadragon453** [comment]
I wonder if this is related to https://github.com/matrix-org/synapse/issues/9962 (fixed in v1.35.0).

**Comment by babolivier** [comment]
I think it might be yes.

**Comment by jaywink** [comment]
Have updated to v1.35.0, will confirm whether issue disappears.

**Comment by jaywink** [comment]
Unfortunately the issue persists. After restart I saw myself online (on federator.dev) for a while and am now offline again. Also I still see no one online from vector, which also was updated to v1.35.0.

I can see presence of some people on their own HS's who may or may not be running a presence worker (assuming that matters). These include @erikjohnston and @daenney who consistently show online for me.

Could this be a configuration thing, given both federator and vector run in EMS? I could try remove the presence workers to see if that matters?

**Comment by daenney** [comment]
In my case I'm not running with a presence worker. My HS is the all-in-one no workers anywhere setup.

**Comment by jaywink** [comment]
@erikjohnston I'm reopening as presence for myself is still showing as offline. What is fixed is that I can now see presence for users on vector, which is a major improvement. But for myself, after a little while after homeserver restart, I see myself offline again.

**Comment by jaywink** [comment]
Actually, federator was never updated to v1.36.0, *now it is*, so this might be ok after all, will re-re-open if not the case. Thanks!
